In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import os
from PIL import Image

In [2]:
image_path = "/home/yura/Desktop/image_dataset/"
out_jpg = "/home/yura/Desktop/image_dataset/output/"
cascade_path = "/home/yura/anaconda3/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml"

In [3]:
#get file list
def get_file(dir_path):
    dir_list = os.listdir(dir_path)
    filenames = [f for f in dir_list if os.path.isfile(os.path.join(dir_path, f))]
    return filenames

#read file
image = get_file(image_path)

for i in image:
    image_gs = cv2.imread(image_path + i)
    
    #convert to grayscale
    image_gray = cv2.cvtColor(image_gs, cv2.COLOR_BGR2GRAY)

    #CascadeClassifier
    cascade = cv2.CascadeClassifier(cascade_path)

    #face recognition (detect face)
    facerect = cascade.detectMultiScale(image_gray, scaleFactor=1.2, 
                                        minNeighbors=2, minSize=(10, 10))

    print (str(i))
    print (facerect)
    
    #face crop
    j = 1;
    for rect in facerect:
        dst = image_gs[rect[1]:rect[1] + rect[3], rect[0]:rect[0] + rect[2]]
        save_path = out_jpg + '/' + 'out_('  + str(i) +')' + str(j) + '.jpg'
        
        #save
        cv2.imwrite(save_path, dst)
        #plt.show(plt.imshow(np.asarray(Image.open(save_path))))
        j += 1

hl.jpg
[[480 194  54  54]
 [627 223  46  46]
 [294 211  48  48]
 [817 245  49  49]
 [122 238  45  45]]
Aaron_Eckhart_0001.jpg
[[ 71  67 110 110]]
